version: '2'
services:
  appdaemon:
    image: acockburn/appdaemon:latest
    volumes:
      - ha_config:/conf
    ports:
      - ${PORT}:5050
    restart: always
    environment:
      HA_URL: ${HA_URL}
      HA_KEY: ${HA_KEY}
      DASH_URL: ${DASH_URL}